src/protected/models/Comment.php
<?php

/**
 * This is the model class for table "{{comment}}".
 *
 * The followings are the available columns in table '{{comment}}':
 * @property string $id
 * @property string $content
 * @property string $status
 * @property string $create_time
 * @property string $author
 * @property string $email
 * @property string $url
 * @property string $post_id
 * @property string $ip
 */
class Comment extends CActiveRecord
{
	const STATUS_PENDING=1;
	const STATUS_APPROVED=2;
	const STATUS_SPAM=3;


	public $verifyCode;

	/**
	 * Returns the static model of the specified AR class.
	 * @return Comment the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{comment}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('content, status, author, email, post_id, ip', 'required'),
			array('status, create_time, post_id', 'length', 'max'=>11),
			array('author, email, url', 'length', 'max'=>128),
			array('ip', 'length', 'max'=>15),
			array('verifyCode', 'captcha', 'allowEmpty' => !extension_loaded('gd'), 'captchaAction' => 'site/captcha'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, content, status, create_time, author, email, url, post_id, ip', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'post' => array(self::BELONGS_TO, 'Post', 'post_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'content' => Yii::t(__CLASS__, 'Content'),
			'status' => Yii::t(__CLASS__, 'Status'),
			'create_time' => Yii::t(__CLASS__, 'Create Time'),
			'author' => Yii::t(__CLASS__, 'Author'),
			'email' => Yii::t(__CLASS__, 'Email'),
			'url' => Yii::t(__CLASS__, 'Url'),
			'post_id' => Yii::t(__CLASS__, 'Post'),
			'ip' => Yii::t(__CLASS__, 'Ip'),
			'verifyCode' => Yii::t('all', 'Verify code'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('content',$this->content,true);
		$criteria->compare('status',$this->status,true);
		$criteria->compare('create_time',$this->create_time,true);
		$criteria->compare('author',$this->author,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('url',$this->url,true);
		$criteria->compare('post_id',$this->post_id,true);
		$criteria->compare('ip',$this->ip,true);

		if ( ! $criteria->order)
		{
			$criteria->order = 'create_time DESC';
		}
		
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}


	protected function  beforeSave()
	{
		if (parent::beforeSave())
		{
			if ($this->isNewRecord && ! isset($this->create_time))
			{
				$this->create_time = time();
			}
			return true;
		}
		else
			return false;
	}


	/**
	 * Approves a comment
	 */
	public function approve()
	{
		$this->status = Comment::STATUS_APPROVED;
		$this->update(array('status'));
	}

	/**
	 * Mark as spam
	 * @return void
	 */
	public function spam()
	{
		$this->status = Comment::STATUS_SPAM;
		$this->update(array('status'));
	}

	/**
	 * Return url to the comment
	 * @param Post The post that this comment belongs to. If null, the method will query for the post.
	 * @return string the permalink URL for this comment
	 */
	public function getUrl($oPost=null)
	{
		if($oPost===null)
		{
			$oPost = $this->post;
		}
		return $oPost->getLink() . '#c' . $this->id;
	}

	/**
	 * The hyperlink display for the current comment's author
	 * @return string
	 */
	public function getAuthorLink()
	{
		if ( ! empty($this->url))
		{
			return CHtml::link(CHtml::encode($this->author), $this->url);
		}
		else
		{
			return CHtml::encode($this->author);
		}
	}

	/**
	 * The number of comments that are pending approval
	 * @return integer
	 */
	public function getPendingCommentCount()
	{
		return $this->count('status=' . self::STATUS_PENDING);
	}

	/**
	 * Return the most recently added comments
	 * @param integer the maximum number of comments that should be returned
	 * @return array
	 */
	public function findRecentComments($limit=10)
	{
		return $this->with('post')->findAll(array(
			'condition'=>'t.status='.self::STATUS_APPROVED,
			'order'=>'t.create_time DESC',
			'limit'=>$limit,
		));
	}
}

src/protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow admin user
				'actions'=>array('create','update', 'admin', 'delete'),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id=0, $url='')
	{
		CMarkdown::registerCssFile();
		if ($url)
		{
			$oPost = Post::model()->scopePublished()->find(array(
				'condition' => 'url = :url',
				'params' => array(
					':url' => $url,
				)
			));
		}
		else
		{
			$oPost = $this->loadModel($id);
			//$this->redirect('/' . $oPost->url);
		}
		if ( ! $oPost)
		{
			throw new CHttpException(404);
		}

		// rss for comments
		Yii::app()->clientScript->registerLinkTag(
			'alternate',
			'application/rss+xml',
			Yii::app()->createAbsoluteUrl($oPost->getLink(true)) . '/rss/',
			null,
			array(
				'title' => 'Комментарии к статье: ' . $oPost->title,
			)
		);
		$this->pageTitle = $oPost->title;
		$aComments = $oPost->comments;
		$oComment = $this->newComment($oPost);
		$this->render('view',array(
			'model'=>$oPost,
			'comment' => $oComment,
			'aComments' => $aComments,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}
		elseif ( ! $model->post_time)
		{
			$model->post_time = date('Y-m-d');
		}


		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		$aTags = array();
		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}
		else
		{
			if ($model->tags)
			{
				foreach ($model->tags as $oTag)
				{
					$aTags[] = $oTag->name;
				}
			}
			//Set post time field default to today
			if ( ! $model->post_time)
			{
				$model->post_time = date('Y-m-d');
			}
			else
			{
				$model->post_time = date('Y-m-d', $model->post_time);
			}
		}

		$model->tags_string = Tag::array2string($aTags);


		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all posts
	 * @throws CHttpException
	 * @param null $tag
	 * @return void
	 */
	public function actionIndex($tag=null)
	{
		CMarkdown::registerCssFile();
		// Get last update_time of post for cache dependency
		$iDependencyPost = Post::model()->find(array(
			'select' => 'MAX(update_time) AS update_time',
		));
		$iDependencyPost = $iDependencyPost ? $iDependencyPost->update_time : 0;
		Yii::app()->setGlobalState('post.update_time', $iDependencyPost);
		$dependencyPost = new CGlobalStateCacheDependency('post.update_time');

		$dependencyTag = new CDbCacheDependency('SELECT MAX(id) FROM {{tag}}');


		$criteria=new CDbCriteria(array(
			'order'=>'create_time DESC',
			'scopes' => 'scopePublished',
		));
		// If use tag
		if (isset($tag))
		{
			if ($oTag = Tag::model()->cache(Yii::app()->params['cacheTime'], $dependencyTag)->findByAttributes(array(
				'name' => $tag,
			)))
			{
				$aPostIds = Yii::app()->db->cache(Yii::app()->params['cacheTime'], $dependencyPost)->createCommand()
					->select('post_id')
					->from('{{post_tag}}')
					->where('tag_id = :tagId', array(
						'tagId' => $oTag->id,
					))
					->queryColumn();
				$criteria->addInCondition('t.id', $aPostIds);
			}
			else
			{
				$criteria->addCondition('id = 0');
				throw new CHttpException(404, Yii::t('all', 'No such tag'));
			}
		}
		
		$criteria->with = 'commentCount';

		$dataProvider = new CActiveDataProvider(Post::model()->cache(Yii::app()->params['cacheTime'], $dependencyPost, 2), array(
			'pagination'=>array(
				'pageSize'=>Yii::app()->params['postsPerPage'],
				'pageVar' => 'page',
				'params' => array(),
			),
			'criteria'=>$criteria,
		));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Post('search');
		$model->unsetAttributes();  // clear any default values
		// By default sort by id
		$model->getDbCriteria()->mergeWith(array(
			'order' => 'id DESC',
		));
		if(isset($_GET['Post']))
			$model->attributes=$_GET['Post'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Post::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='post-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	protected function newComment($post)
	{
		$oComment = new Comment;

		$cookie_keys = array('author', 'email', 'url');

		if (isset($_POST['Comment']))
		{
			$oComment->attributes=$_POST['Comment'];
			if (isset($_POST['ajax']) && $_POST['ajax'] == 'comment-form')
			{
				echo CActiveForm::validate($oComment);
				Yii::app()->end();
			}
			if ($post->addComment($oComment))
			{
				foreach($cookie_keys as $field)
				{
					$field_cookie = 'form_' . $field;
					$cookie=new CHttpCookie($field_cookie, $oComment->{$field});
					$cookie->expire = strtotime('+1 year');
					Yii::app()->request->cookies[$field_cookie]=$cookie;
				}
				if ($oComment->status == Comment::STATUS_PENDING)
				{
					Yii::app()->user->setFlash('commentSubmitted', 'Спасибо за комментарий! Сейчас он находится на модерации, но скоро появится ;)');
				}
				$this->refresh(true, '#c' . $oComment->id);
			}
		}
		else
		{
			foreach($cookie_keys as $field)
			{
				$field_cookie = 'form_' . $field;
				if (Yii::app()->request->cookies[$field_cookie])
				{
					$oComment->{$field} = Yii::app()->request->cookies[$field_cookie]->value;
				}
			}
		}
		return $oComment;
	}
}

src/protected/views/post/_comments.php
<ol class="comments">
<?php $first = false; ?>
<?php foreach($comments as $comment): ?>
	<li class="comment<?php echo ! $first ? ' first' : '' ?>" id="c<?php echo $comment->id; ?>">
		<?php $first = true; ?>
		<div class="head">
			<span class="link">
				<?php echo $comment->authorLink; ?>
				<?php echo CHtml::link("#", $comment->getUrl($post), array(
				'class'=>'cid',
				'title'=>'Ссылка на комментарий',
			)); ?>
			</span>
			<div class="avatar">
				<img src="http://www.gravatar.com/avatar/<?php echo md5($comment->email);?>/?s=36" alt="<?php echo $comment->author; ?>" />
			</div>
			<span class="date">[<?php echo date('Y-m-d H:i',$comment->create_time); ?>]</span>
		</div>

		<div class="content">
			<?php echo Escape::escapeHtml($comment->content); ?>
		</div>

	</li><!-- comment -->
<?php endforeach; ?>
</ol>

src/protected/views/post/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'post-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note"><?php echo Yii::t('all', 'Fields with <span class="required">*</span> are required'); ?>.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'title'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'content'); ?>
		<?php $this->widget('ext.markitup-widget.EMarkitupWidget', array(
			'model' => $model,
			'attribute' => 'content',
			'settingsUrl' => '/static/markitup',
			'settings' => 'comment',
		))?>
		<?php echo $form->error($model,'content'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'status');?>
		<?php echo $form->dropDownList($model,'status', Lookup::items('PostStatus')); ?>
		<?php echo $form->error($model,'status'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'post_time'); ?>
		<?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
			'model' => $model,
			'attribute'=>'post_time',
			//'name'=>'post_time',
			'value' => $model->post_time,
			'language' => 'ru',
			'options'=>array(
				'showAnim'=>'fold',
				'dateFormat' => 'yy-mm-dd',
			),
			'htmlOptions'=>array(
				'style'=>'height:20px;'
			),
		));
		?>
		<?php echo $form->error($model,'post_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'url'); ?>
		<?php echo $form->textField($model,'url',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'url'); ?>
		<?php
			$cs=Yii::app()->clientScript;
			$cs->registerCoreScript('synctranslit');
			$cs->registerScript('url-translit', '$("#Post_title").syncTranslit({destination: "Post_url"});', CClientScript::POS_READY);
		?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'tags_string'); ?>
		<?php
			$this->widget('zii.widgets.jui.CJuiAutoComplete', array(
				'model'=>$model,
				'attribute'=>'tags_string',
				'value'=>$model->tags_string,
				'source' =>'js:function(request, response) {
					jQuery.getJSON("'.$this->createUrl('tools/tagsautocomplete').'", {
						query: request.term.split(/,s*/).pop()
					}, response);
				}',
				'options' => array(
					'minLength' => '2',
					'showAnim' => 'fold',
					'search' =>'js: function() {
						var term = this.value.split(/,s*/).pop();
						if(term.length < 2)
							return false;
					 }',
					'focus' =>'js: function() {
						return false;
					 }',
					'select' =>'js: function(event, ui) {
						var terms =  this.value.split(/,s*/);
						terms.pop();
						terms.push(ui.item.value);
						terms.push("");
						this.value = terms.join(", ");
						return false;
					}',
				),
				'htmlOptions'=>array(
					'style'=>'height:20px;'
				),
			));
		?>
		<?php echo $form->error($model,'tags_string'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? Yii::t('all', 'Create') : Yii::t('all', 'Save')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

src/protected/views/post/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'content'); ?>
		<?php echo $form->textArea($model,'content',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'content_display'); ?>
		<?php echo $form->textArea($model,'content_display',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_time'); ?>
		<?php echo $form->textField($model,'create_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'update_time'); ?>
		<?php echo $form->textField($model,'update_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'post_time'); ?>
		<?php echo $form->textField($model,'post_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'author_id'); ?>
		<?php echo $form->textField($model,'author_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'url'); ?>
		<?php echo $form->textField($model,'url',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'short_url'); ?>
		<?php echo $form->textField($model,'short_url',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

src/protected/views/post/_view.php
<div class="note">

	<?php $link = $data->getLink(); ?>
	<h1><?php echo CHtml::link($data->title, $link); ?></h1>
	<span><?php echo Yii::app()->dateFormatter->format('d MMMM', $data->update_time); ?></span>
	<div class="text">
		<?php echo $data->content_display; ?>
	</div>
	<?php $count = $data->commentCount; ?>
	<?php echo CHtml::link(
		Yii::t('Comment', '{n} comment|{n} comments', $count),
		$link);
	?>

</div>

src/protected/views/post/admin.php
<?php
$this->breadcrumbs=array(
	Yii::t('Post', 'Posts')=>array('index'),
	Yii::t('Post', 'Manage'),
);

$this->menu=array(
	array('label'=>Yii::t('Post', 'List Post'), 'url'=>array('index')),
	array('label'=>Yii::t('Post', 'Create Post'), 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('post-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Posts</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'post-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'title',
		'content_display:html',
		array(
			'name' => 'status',
			'filter' => Lookup::items('PostStatus'),
			'type' => 'raw',
			'value' => 'Lookup::item("PostStatus", $data->status)',
		),
		array(
			'name' => 'post_time',
			'type' => 'raw',
			'value' => 'date("Y-m-d H:i:s", $data->post_time)',
		),
		/*
		'update_time',
		'post_time',
		'author_id',
		'url',
		'short_url',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

src/protected/views/post/create.php
<?php

$this->pageTitle = Yii::t('Post', 'Create Post');

$this->breadcrumbs=array(
	Yii::t('Post', 'Posts')=>array('index'),
	Yii::t('All', Yii::t('all', 'Create')),
);

$this->menu=array(
	array('label'=>Yii::t('Post', 'List Post'), 'url'=>array('index')),
	array('label'=>Yii::t('Post', 'Manage Post'), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('Post', 'Create Post');?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

src/protected/views/post/index.php
<?php
$this->breadcrumbs=array(
	Yii::t('all','Posts'),
);

$this->menu=array(
	array('label'=>Yii::t('Post','Create Post'), 'url'=>array('create')),
	array('label'=>Yii::t('Post','Manage Post'), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('all','Posts')?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

src/protected/views/post/update.php
<?php
$this->breadcrumbs=array(
	Yii::t('all','Posts')=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	Yii::t('all', 'Update'),
);

$this->menu=array(
	array('label'=>Yii::t('Post', 'List Post'), 'url'=>array('index')),
	array('label'=>Yii::t('Post', 'Create Post'), 'url'=>array('create')),
	array('label'=>Yii::t('Post', 'View Post'), 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>Yii::t('Post', 'Manage Post'), 'url'=>array('admin')),
);
?>

<h1>Update Post <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

src/protected/views/post/view.php
<?php
$this->breadcrumbs=array(
	Yii::t('Post', 'Posts')=>array('index'),
	$model->title,
);

$this->menu=array(
	array('label'=>Yii::t('Post', 'List Post'), 'url'=>array('index')),
	array('label'=>Yii::t('Post', 'Create Post'), 'url'=>array('create')),
	array('label'=>Yii::t('Post', 'Update Post'), 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>Yii::t('Post', 'Delete Post'), 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('Post', 'Manage Post'), 'url'=>array('admin')),
);

/*$cs = Yii::app()->getClientScript();
$cs->registerScriptFile('/static/js/fancybox/jquery.fancybox-1.3.4.pack.js', CClientScript::POS_HEAD)
    ->registerScriptFile('/static/js/fancybox/jquery.easing-1.3.pack.js', CClientScript::POS_HEAD)
    ->registerScriptFile('/static/js/fancybox/jquery.mousewheel-3.0.4.pack.js', CClientScript::POS_HEAD)
    ->registerCssFile('/static/js/fancybox/jquery.fancybox-1.3.4.css')
    ->registerScriptFile('http://userapi.com/js/api/openapi.js?31', CClientScript::POS_HEAD);*/

?>


<h1 class="inline"><?php echo CHtml::link(CHtml::encode($model->title), array('view', 'id'=>$model->id, 'title'=>$model->title)); ?></h1>
<span class="hint"><?php echo Yii::app()->dateFormatter->format('d MMMM', $model->post_time); ?></span>

<div class="article">
	<?php echo $model->content_display; ?>
</div>

<b><?php echo CHtml::encode($model->getAttributeLabel('tags')); ?>:</b>
<?php echo $model->tagsLink(); ?>


<div id="social-buttons">
</div>

<div id="comments">
	<?php if ( ! empty($model->commentCount) && $model->commentCount >= 1): ?>
		<h3>
			<?php echo Yii::t('Comment', '{n} comment|{n} comments', $model->commentCount); ?>:
		</h3>
		<a name="comments"></a>
		<?php $this->renderPartial('_comments',array(
			'post'=>$model,
			'comments'=>$aComments,
		)); ?>
	<?php endif; ?>


	<h3 style="padding-top:20px;"><?php echo Yii::t('Post', 'Leave comment');?></h3>
	<?php if (Yii::app()->user->hasFlash('commentSubmitted')) { ?>
		<div class="flash-success">
			<?php echo Yii::app()->user->getFlash('commentSubmitted'); ?>
		</div>
	<?php } else { ?>
		<?php $this->renderPartial('/comment/_form',array(
			'model'=>$comment,
		)); ?>
	<?php } ?>
</div>

<script type="text/javascript">
jQuery(document).ready(function() {
	//$("a.images").fancybox();
	$("a.images").fancybox({
		'transitionIn'	:	'elastic',
		'transitionOut'	:	'elastic',
		'speedIn'		:	600,
		'speedOut'		:	200,
		'overlayShow'	:	true,
		'overlayOpacity'	: 0.9,
		'overlayColor': 'black'
	});
});
</script>
<script type="text/javascript">
VK.Widgets.Like("vk_like", {type: "mini", pageTitle: "<?php echo str_replace('"', '\\"', $model->title); ?>"}, <?php echo $model->id; ?>);
</script>

<!-- Place this tag just before your close body tag -->
<script>
(function(d, t) {
var g = d.createElement(t),
s = d.getElementsByTagName(t)[0];
g.async = true;
g.src = 'https://apis.google.com/js/plusone.js';
s.parentNode.insertBefore(g, s);
})(document, 'script');
</script>